server:
  port: 9001
  servlet:
    context-path: /api/v1

logging:
  level:
    root: info
    top.houyuji: debug

spring:
  application:
    name: easy-admin

mybatis-plus:
  mapper-locations:
    - classpath*:mapper/*.xml
    - classpath*:top/houyuji/**/xml/*.xml
  configuration:
    map-underscore-to-camel-case: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 返回类型为Map,显示null对应的字段
    call-setters-on-nulls: true
  global-config:
    banner: true